### ISSUE TITLE
Preview of images/docs in chat

### ISSUE THREAD

**Issue by vickyjain05** [redsolution/xabber-web#17]
In Xabber for web, when I send a file it shows up a link like this: 
![uknowva messenger 10](https://user-images.githubusercontent.com/15120330/38466354-8f91c946-3b45-11e8-8bb5-92705519aff2.png)

Can we show the preview of it? like it happens in the mobile app?

**Comment by andrewnenakhov** [comment]
It can be shown, yes, but it can't be done in a very straighforward way, because if you simply put <img src=''> it can open a security vulnerability, you need to sanitise incoming urls.

**Comment by vickyjain05** [comment]
Agreed, but currently also the urls are open...but a bit sanitsed i think..showing them as preview might at least not show the raw url, could be an enhancement in security and i think u r already doing this in the mobile app, just the same needs to be done in web as well :)

**Comment by andrewnenakhov** [comment]
@vickyjain05 issue is not with previews. Issue is with malicious code that can be sent to you by remote partner and could potentially do anything to your browser, including stealing your password.

Anyway we're preparing an update that'll be showing images right in chat.

**Comment by vickyjain05** [comment]
Got it, let me know once the update is there.....may be we can just have previews for selected files only like jpeg, pdf, etc....to avoid script injections

**Comment by andrewnenakhov** [comment]
Actually it's implemented already, check latest commits. We're working on some more though, like sending audio messages.

**Comment by anyuta1166** [comment]
Hmm... I use Conversations XMPP client for Android.

Images sent from Conversations appears as an image in Conversations, but as a text link in Xabber Web.
And vice versa.
Images sent from Xabber Web appears as an image in Xabber Web, but as a text link in Conversations.

What is this? Different implementation of XEP-0363: HTTP File Upload?

Any fix possible, and on which side it should be done?

**Comment by andrewnenakhov** [comment]
Conversations use different format to send image location. We do not support that format because it does not allow to efficiently and coherently pass over necessary metadata so the client can efficiently process and display sent media. We do not plan to support the format used by Conversation. If you want full compatibility on all platforms, use Xabber for Android or Xabber for iOS (due to release soon), they work seamlessly with each other.

**Comment by andrewnenakhov** [comment]
Xabber supports images preview, voice messages preview, and other types of media. I believe it is safe to close the issue.

![xabberwebscreenshot](https://user-images.githubusercontent.com/2351903/90031085-452e5d80-dcd6-11ea-90fe-a5e1a2118c32.png)

**Comment by anyuta1166** [comment]
It's a pity. That's the biggest flaw of XMPP. Tons of XEPs and everyone pulls the blanket over themselves supporting the set of XEPs they want and making incompatible applications :-(

**Comment by andrewnenakhov** [comment]
@anyuta1166 because we have an outreaching plan for XMPP. Thing is, http file upload as it works today is a potential breach of user privacy: If i send you an image that I know that your client will download for displaying, it will disclose your IP location to my http upload server. Now, while this is still true for our data sending format, our future goal is to create an extension to the user server that will act as a proxy for incoming media and will store it for user retrieval. So the potential attacker will not see the IP of the client, only the IP of his server. Our new media exchange format is more suitable for that. 

Also, XMPP standards suffers from standards being published with little regard for prior work and other purposes. It is a nightmare for developers. We came up with a common format that has a unified approach to everything a message can contain: images, formatting, video, mentions, voice messages, video messages, geolocation, stickers, url snippets, hashtags.  It also provides a natural fallback for legacy clients.
