### ISSUE TITLE
OTR Support

### ISSUE THREAD

**Issue by netzgestaltung** [redsolution/xabber-web#2]
Hi there,

i was wondering if there is an option to activate OTR on the webinterface like on https://www.libervia.org/ or https://jabber.at/chat (with converse.js)

both of these services have their own downsides which made me looking for alternatives, so me and my girlfriend (she cant install anything on her companies computer) startet testing https://web.xabber.com/ yesterday.

**Comment by andrewnenakhov** [comment]
OTR is not yet implemented in Xabber for Web, but it is coming. Eventually.

**Comment by netzgestaltung** [comment]
Thank you for evaluating!

Should i post other issues as well which may come out while testing?

**Comment by andrewnenakhov** [comment]
That's what this issue tracker is for! )

**Comment by andrewnenakhov** [comment]
We've implemented OMEMO #3  encryption, and OTR is kinda obsolete these days, so i'm rejecting this

**Comment by netzgestaltung** [comment]
omemo is kind of beta from my pidgin experience point of view - the lurch plugin is unmaintained since years: https://github.com/gkdr/lurch so i and other buddys rely on OTR still. Do you have an alternate recommendation for a desktop Multimessenger (GTK3)?

**Comment by andrewnenakhov** [comment]
@netzgestaltung well, you can run Xabber for Web as a 'desktop multimessenger' actually. I do it all the time. Xabber for Web was built as a no-compromise desktop xmpp client, and I think we're 80% there. Eventually we'll make a destop version of in via Electron wrapper. Native version would be better of course but we don't have funds to build a fourth client now (first three being Android, iOS and Web versions). 

We decided to track back on OTR because we came to realization that any standard that can't properly work on all platforms (mobile OSs, desktop OSs, browsers) is flawed and should be discarded. OTR certainly can't really work on iOS devices, so it makes no sense to us to implement it across our apps.

**Comment by andrewnenakhov** [comment]
@netzgestaltung i personally use Xabber as a 'desktop multimessenger' :-) 

eventually we'll make a desktop version using electron wrapper. Maybe if we get some serious funding, we'll eventually even make a native desktop app.

**Comment by netzgestaltung** [comment]
interesting. i avoid electron and browser apps as much as i can. does Xabber handles Steam, Facebook, and other protocols? i thought it was only for XMPP...

**Comment by andrewnenakhov** [comment]
@netzgestaltung electron is not ideal, but helps bring an web app to desktop quickly. As for Steam, Facebook, etc - they don't have open protocols, and Facebook in particular is openly hostile to any third-party clients, so trying to create a multiprotocol messenger is a fool's errand. You will always play catch-up with all new features that change very often. 

That said, you can always try running an XMPP transport to bring messages from those services to XMPP.
