### ISSUE TITLE
OMEMO support

### ISSUE THREAD

**Issue by tdemin** [redsolution/xabber-web#3]
Yes, this is a feature request and this issue is meant to be used to track things. ;-)

https://xmpp.org/extensions/xep-0384.html

**Comment by tigre-bleu** [comment]
I'm also waiting for this before using Xabber-web. Most of my contacts use OMEMO with Conversation client.

**Comment by joe-average-user** [comment]
Ah, that's the reason why nobody I ever heard of uses this. Really by far the most-used client is Conversations on Android, and just about everyone uses OMEMO there. Which means you cannot interact with a very large part of the XMPP community...
I would not have found you without the link on XMPP.org anyway. Your screenshots look great, but without encryption this is useless.
Really sorry...

**Comment by andrewnenakhov** [comment]
Lol. @joe-average-user , Just look at install counts on Google Play. Also, if you have a common cryptofetish with your friends, that doesn't mean that everyone else has it too. 

(We're intentionally rude to omemo guys because most of them abuse all of our issue trackers, by stubbornly insisting that their  rarely used feature is of such paramount importance that we should break everything else just to satisfy their fetishist desire to 'not being spied upon')

Begone, please. Return when you have 2btc to actually pay for what you want.

**Comment by joe-average-user** [comment]
Lol. you probably have no idea about Android either. Else you would know FDroid, where all the GPL software is to find _free_ - and Conversations is GPL. The Google Play downloads represent only people that wanted to pay for Conversations, which is of course a good thing for the author. And btw, I honestly doubt that your software was downloaded even in such numbers taking into account that only 15 people are watching the project.
As the OP said, OMEMO is a XMPP standard definition XEP-0384. You should not be surprised by low user counts if you don't want to follow the standards XMPP provides.

**Comment by andrewnenakhov** [comment]
@joe-average-user you are typical clueless omemodiot. Omemo isn't a standard, not even a draft. Next time you come telling us to do, have money in your pocket.

**Comment by andrewnenakhov** [comment]
actually it was implemented a few months ago.
