### ISSUE TITLE
Are configuration options working?

### ISSUE THREAD

**Issue by anyuta1166** [redsolution/xabber-web#43]
Hello.
I've installed xabber web to my own web server to work in conjuction with my own ejabberd server.
Version - latest git master.

There is a wiki https://github.com/redsolution/xabber-web/wiki that mentions some config options, namely:

USE_SOCIAL_AUTH - true/false, if set to true, Social Authorisation to Xabber Account is available. Default value is true.

DEFAULT_LOGIN_SCREEN - 'xabber' or 'xmpp', which auth type would be displayed first on welcome screen. Default value is 'xabber'.

Are they working?

If I set USE_SOCIAL_AUTH = false, the social auth icons still appear on the login page.
DEFAULT_LOGIN_SCREEN = 'xmpp' does nothing too. What is it meant to do?

I don't need xabber accounts. I want to use xabber web only as web ui to my own xmpp server.

**Comment by anyuta1166** [comment]
The reason I tried to use xabber web for this purpose is that I didn't find any other correctly working xmpp web client.

The only alternative I've found is converse.js, but it has a fatal bug that floods the database with message receipts and it is not getting fixed.

**Comment by andrewnenakhov** [comment]
@anyuta1166 the reason converse floods database is because they use this ugly hack to sync read status between different clients. It is a serious problem in XMPP because XEP-0313 Message Archive does not have a way to mark messages as read.

Actually, to combat this issue (among many others) and make a web and iOS clients work well we had to bite the bullet and develop our own [server](https://github.com/redsolution/xabber-server/). Our key principle is that we rather radically change how server interacts with a clients, but leave the federation part intact. Our notable changes to server is addition of quick synchronization protocol, support for editing messages, new advanced group chat protocol, reliable message delivery protocol, and also the push notification extension that CAN work on modern iOS devices, unlike the one described in XEP-0357

Quick synchronization protocol lets clients retrieve latest conversations from server, including the counters of read/unread/seen messages, splitting encrypted conversations from open ones. Others are self-explanatory, I guess.

**Comment by anyuta1166** [comment]
> the reason converse floods database is because they use this ugly hack to sync read status between different clients.

@andrewnenakhov But xabber web works flawlessly even with ejabberd.

**Comment by anyuta1166** [comment]
What's about the topic of this issue? Are configuration options working?

**Comment by valeria-gh** [comment]
@anyuta1166 You can use the xabber web version from the /develop branch or wait for tomorrow's release

**Comment by andrewnenakhov** [comment]
>  But xabber web works flawlessly even with ejabberd. And doesn't flood the database.

@anyuta1166 well, thank you, it took a lot of hard work but in my opinion it is far from being flawless. First off, with ejabberd on first login Xabber has to fetch last message from archive for every contact. With rosters of 300+ contacts this becomes a real pain and takes 5-7 minutes to do. Second, all messages are treated as 'read', because we can't really know their status. 

Xabber Server fixes this by [XEP-SYNC](https://xabber.com/protocol/synchronization) protocol, which allows efficient fetching of recent conversations in reversed chronological order, as well as unread counters, etc. The work is not done completely: XEP-SYNC currently lacks such information as user's nickname, so at first contacts appear as XMPP Ids, but it's a start. I won't be satisfied until Xabber for Web loads all necessary information in 3-5 seconds after login.

**Comment by anyuta1166** [comment]
> You can use the xabber web version from the develop branch

@valeria-gh xabber web form develop branch doesn't work.

I've made make deps-install; make minify and copied resulting files from /dist to the web server directory overwriting files from 2.0.2 release.
Now I see the blank gray page in a browser. Reverting to the last release - all works fine.

**Comment by anyuta1166** [comment]
I've tried to set
```
 LOG_LEVEL: 'INFO',
 DEBUG: true,
```
as in example_dev.html, but it gave me no info. Browser console is blank, no messages here.

**Comment by anyuta1166** [comment]
master branch works fine if I build it manually, so the problem is not on my side.

**Comment by valeria-gh** [comment]
> as in example_dev.html, but it gave me no info. Browser console is blank, no messages here.

We changed client rendering logic, but forgot to change example index files. It is fixed. Try again, please.

**Comment by anyuta1166** [comment]
> We changed client rendering logic, but forgot to change example index files. It is fixed. Try again, please.

Thank you, Valeria. It works now
