### ISSUE TITLE
Translate to Spanish

### ISSUE THREAD

**Issue by lexcorp** [redsolution/xabber-web#50]
I want translate Xabber Web to Spanish, but I don’t know how... Can you provide me a guide? Please...

**Comment by andrewnenakhov** [comment]
@lexcorp currently, Xabber for Web does not have internationalization, and will not have it for quite some time. The reason is that we now have three different versions of Xabber (for iOS, Android, and Web), of which only one supports i19n. And it frankly makes little sense to translate them separately - we do not want to have 3 different translation projects in Crowdin, most of them fully duplicating each other. But merging string usage in different versions is a rather big task, that requires tight coordination between develpers of these three versions. We plan to get to it, but only when we're mostly happy with basic features available to users. When we're done, you'll be able to translate all Xabber versions at once, here: https://crowdin.com/project/xabber
