### ISSUE TITLE
Add CSS animated emojis☺

### ISSUE THREAD

**Issue by uchchishta** [redsolution/xabber-web#7]
You know this would be cool ;)

**code:** https://github.com/robertsLando/animated-emojy

##### PREVIEW: http://htmlpreview.github.io/?https://github.com/robertsLando/animated-emojy/blob/master/index.html

![CSS animated emoji](https://camo.githubusercontent.com/372b529dc7b2f8d4aa9377154475bad3923e5330/68747470733a2f2f63646e2e6472696262626c652e636f6d2f75736572732f34333736322f73637265656e73686f74732f313932353730382f656d6f6a69732e676966)

**Comment by andrewnenakhov** [comment]
Hell NO! Animated emojis will make chat experience very distracting, and will turn app into some viber-like abomination.

We are working on creating continuous chat environment on all supported platforms, so we are set on using [Apple's set of Emojis](https://emojipedia.org/apple/), because they are most recognisable and most coherent set available.
